spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
#    console.enabled: true # Enabled database console on http://localhost:8080/h2-console, uncomment to use it
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

springdoc:
  packagesToScan: com.github.njsuarez.prices.application
  api-docs:
    path: /api-docs
